apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  region: ${REGION}
  version: "${K8S_VERSION}"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: false
addons:
- name: vpc-cni
- name: kube-proxy
- name: coredns

