apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: custom-net-throughput-metrics
spec:
  parser:
    tcp:
      enable: true
      statsInterval: 60
    udp:
      enable: true
      cgroup: true
      statsInterval: 60
