global:
  environment:
    enabled: true
    profiles:
      - aws-eks
      - containerd

  alertRules:
    predefinedWorkloads:
      tetragon:
        namespaces:
          - kube-system
        podLabels:
          - app.kubernetes.io/part-of=tetragon
      cilium:
        namespaces:
          - kube-system
        podLabels:
          - app.kubernetes.io/part-of=cilium

    alertCelExprs:
      - expression: >-
          has(ev.process.pod) ?
            !(
              (
                has(ev.process.pod.namespace)
                && ev.process.pod.namespace == 'kube-system'
                && has(ev.process.pod.pod_labels)
                && 'app.kubernetes.io/part-of' in ev.process.pod.pod_labels
                && (
                  ev.process.pod.pod_labels['app.kubernetes.io/part-of'] == 'tetragon'
                  || ev.process.pod.pod_labels['app.kubernetes.io/part-of'] == 'cilium'
                )
              )
              || (
                has(ev.process.pod.namespace)
                && ev.process.pod.namespace == 'kube-system'
                && has(ev.process.pod.pod_labels)
                && (
                  ('k8s-app' in ev.process.pod.pod_labels && ev.process.pod.pod_labels['k8s-app'] == 'kube-dns')
                  || ('eks.amazonaws.com/component' in ev.process.pod.pod_labels && ev.process.pod.pod_labels['eks.amazonaws.com/component'] == 'coredns')
                )
              )
              || (
                has(ev.process.pod.namespace)
                && ev.process.pod.namespace == 'kube-system'
                && has(ev.process.pod.pod_labels)
                && (
                  ('app.kubernetes.io/name' in ev.process.pod.pod_labels && ev.process.pod.pod_labels['app.kubernetes.io/name'] == 'metrics-server')
                  || ('app.kubernetes.io/instance' in ev.process.pod.pod_labels && ev.process.pod.pod_labels['app.kubernetes.io/instance'] == 'metrics-server')
                )
              )
              || (
                has(ev.process.pod.namespace)
                && ev.process.pod.namespace == '${PROM_NAMESPACE}'
              )
            )
          : true

rules:
  exec:
    all:
      interactiveShellExec:
        enabled: true
      interactiveShellExit:
        enabled: true
      interactiveShellFollowup:
        enabled: true

  path:
    all:
      directoryTraversal:
        enabled: true

