kind: CiliumNetworkPolicy
apiVersion: cilium.io/v2
metadata:
  name: vulhub-cnp
  namespace: vulhub
spec:
  endpointSelector: {}
  # Allow all egress traffic (no drops), plus DNS L7 visibility rule
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  - toFQDNs:
    - matchPattern: '*'
  - toEntities:
    - all

